version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on: []
    networks:
      - nekomimi-network

  ui:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - NEXT_PUBLIC_WS_URL=http://localhost:8001
    depends_on:
      - api
    networks:
      - nekomimi-network

networks:
  nekomimi-network:
    driver: bridge